### ISSUE TITLE
[Vue warn]: Invalid prop: type check failed for prop "zIndex"

### ISSUE THREAD

**Issue by meiliujun** [shiye515/vue-sticky#2]
props 中 zIndex 限制type 为Number类型导致 以下vue warning报错

vue.runtime.common.js:589 [Vue warn]: Invalid prop: type check failed for prop "zIndex". Expected Number, got String.

found in

---> <Sticky>
       <App> at C:\Users\viruser.v-desktop\Desktop\vue-sticky-master\example\App.vue
         <Root>

**Comment by meiliujun** [comment]
建议 zIndex  限制 改为 type: [String]

**Comment by shiye515** [comment]
props前面加个冒号（多去看看vue的模版语法）
